// Generated by CoffeeScript 1.8.0
(function() {
  var apiRoomStatus, apiScheduleList, getRoomStatus, getSchedules, lastSchedules, roomIds, rooms, _updateRoomStatus;
  lastSchedules = [];
  rooms = {};
  roomIds = [2246, 2319, 3622, 6186, 41430];
  apiScheduleList = "http://douyu.sashi-con.info/api/list";
  apiRoomStatus = "http://www.douyutv.com/api/client/room/";
  getSchedules = function() {
    return $.get(apiScheduleList, function(data, status, xhr) {
      var schedules;
      schedules = JSON.parse(data);
      return lastSchedules = schedules;
    });
  };
  getRoomStatus = function() {
    var i, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = roomIds.length; _i < _len; _i++) {
      i = roomIds[_i];
      _results.push($.get("" + apiRoomStatus + i, function(data) {
        var roomStatus;
        roomStatus = JSON.parse(data);
        console.log("fetched room status: " + roomStatus.data.room_id);
        return _updateRoomStatus(roomStatus);
      }));
    }
    return _results;
  };
  _updateRoomStatus = function(roomStatus) {
    var roomId;
    if (roomStatus.error === 0) {
      roomId = parseInt(roomStatus.data.room_id) | 0;
      rooms[roomId] = roomStatus.data;
      return console.log("roomStatus updated: " + roomId);
    }
  };
  getSchedules();
  getRoomStatus();
  return setInterval(getSchedules, 300000);
})();
