// Generated by CoffeeScript 1.8.0
(function() {
  var getRoomStatus, getSchedules, roomIds;
  getSchedules = function() {
    var xhr;
    xhr = new XMLHttpRequest();
    xhr.open("GET", "http://localhost:3434/api/list", true);
    console.log("xhr opend");
    xhr.onreadystatechange = function() {
      var schedules;
      console.log("change on ready" + xhr.readyState);
      if (xhr.readyState === 4) {
        console.log(xhr.responseText);
        schedules = JSON.parse(xhr.responseText);
        console.log(schedules);
      }
    };
    return xhr.send();
  };
  roomIds = [2246, 2319, 3622, 6186, 41430];
  getRoomStatus = function() {};
  return setInterval(getSchedules, 300000);
})();
