// Generated by CoffeeScript 1.8.0
var apiScheduleList, getSchedules, lastSchedules, scheduleChanged, schedules, setBadge;

schedules = [];

scheduleChanged = false;

lastSchedules = [];

apiScheduleList = "http://douyu.sashi-con.info/api/list";

setBadge = function(text) {
  return chrome.browserAction.setBadgeText({
    text: text
  });
};

getSchedules = function() {
  var request;
  request = new XMLHttpRequest();
  request.open("GET", apiScheduleList, true);
  request.onload = function() {
    if (request.status >= 200 && request.status < 400) {
      schedules = JSON.parse(request.responseText);
      if (JSON.stringify(schedules) === JSON.stringify(lastSchedules)) {

      } else {
        setBadge('!');
      }
      lastSchedules = schedules;
    } else {

    }
  };
  request.onerror = function() {};
  return request.send();
};

(function() {
  console.log("background loaded");
  getSchedules();
  return setInterval(getSchedules, 5000);
})();
